iipeace/guider

guider.py

This is a minor patch but hope to help this tool.

Fix format and options to support multiple architecture

---

guider.py

this is patch for adding signal filter with -g option.
we can remove unusable signal info.

Adding signal filter

---

guider.py

Adding generic errors to list and print option

---

guider.py

Fixing process tree bug in top profiler

---

Makefile

This patch makes some change to Makefile to hide the details but shows
the details when "V=1" flag is given.
The build output is as follows:
```
$ make install
PCC      guider.pyc
CC       guiderLib.o
CC       guidermodule.so
INSTALL  guider.pyc
INSTALL  guider
INSTALL  guidermodule.so
```
If "V=1" flag is given, it shows the executed command as follows:
```
$ make install V=1
install -d -m 755 /home/honggyu/usr/share/guider
install -d -m 755 /home/honggyu/usr/sbin
install -d -m 755 /home/honggyu/usr/lib
install guider.pyc /home/honggyu/usr/share/guider/guider.pyc
install guider /home/honggyu/usr/sbin/guider
install guidermodule.so /home/honggyu/usr/lib/guidermodule.so
sed -i "s%PREFIX_DIR=%PREFIX_DIR=/home/honggyu/usr%g" /home/honggyu/usr/sbin/guider
```
Signed-off-by: Honggyu Kim …

build: Apply some refactoring to Makefile

---

guider.py

Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>

Change splitter from '|' to extended ascii '│'

---

guider.py

related reference: https://wikidocs.net/16051.

Fix shebang for supporting virtual environments (#1)

---

guider/guider.py

- when encode flag is disabled on reptop, json format is wrong.
- instead of using raw data,
remove whitespace of data what is by enabled encode flag

fix json format in disabled the encode flag

---

guider/guider.py

- Add option('v') for using Elastic Stack
- if you enable option with 'v', setting elasticflag as True
- ex) guider.py reptop -ev

Add option for using Elastic Stack.

---

guider/guider.py

- Add method 'reportSystemStatElastic'
- Add comments to help section.
- Elastic data include always 2 fields which are metricset and beat fields.

Add method to generate elastic data such as beats platform.

---

guider/guider.py

- Implelement to getnerate cpu data dictionary
: cpu total data

Implement to generate cpu data dictionary

---

guider/guider.py

- Add beatCount field for syncing timestamp
- it seems like missing even if there was no missing data.

Add beatCount field for syncing timestamp

---

agent/__init__.py

1. Modify Flask
2. Add Guider Agent Code

Implement to get Data from Guider Server and print on Flask Web Page.

---

agent/__init__.py

Remove merge conflict markers in agent/__init__.py
Issue #60

Remove merge conflict markers

---

.travis.yml

travis의 낮은 node 버전으로 인한 travis build 에러 수정을 위해 node 10으로 변경 요청합니다.

Change travis node version

---

agent/front-vue/yarn.lock

I have modified yarn.lock in order to fix the vulnerable dependencies by adding the updated versions.

Dependency security issues fix

---

agent/front-vue/yarn.lock

Here it is, just let me know if there are more vulnerable dependencies that must be updated. Thanks!

Lodash Dependencies Updated

---

agent/README.md
agent/app/__init__.py
agent/app/config.py
agent/manage.py
agent/requirements.txt

add app dir and set config
add manage.py for run flask
readme wip

This closes #92 #93 #94

---

agent/front-vue/package.json
agent/front-vue/vue.config.js

change vue project name in config files

---

.travis.yml
agent/.flake8
agent/.gitignore
agent/__init__.py
agent/app/__init__.py
agent/app/config.py
agent/example.py
agent/monitoring/controllers.py
agent/monitoring/services.py

close #104 
travis에 flake8 붙이면서 기존 코드 스타일 조금 수정하였습니다.
또, travis에 있던 npm run build는 아직은 의미가 없는 것 같아 npm run lint로 바꿨습니다.

Add flake8 in travis-ci

---

guider/guider.py

Add clearList function to remove useless values in list

---

agent/app/__init__.py
agent/front-vue/package-lock.json
agent/front-vue/src/layout/DashboardLayout.vue
agent/front-vue/src/pages/Background.vue
agent/front-vue/src/router/routes.js
agent/monitoring/controllers.py
agent/monitoring/services.py

Add flask-cors option in /dataset and /slack
Return empty list when database doesn't exist at /dataset
Print stored database at background page

Print stored databases in background page.

---

agent/app/__init__.py
agent/common/guider.py
agent/front-vue/src/pages/Command.vue
agent/front-vue/src/pages/Dashboard.vue
agent/front-vue/src/pages/SocketIO.vue
agent/monitoring/services.py

command logic wip
move RequestManger class

this resolve #155 resolve #156

---

agent/common/guider.py
agent/front-vue/package-lock.json
agent/front-vue/src/App.vue
agent/front-vue/src/model/guider-graph-data-set.js
agent/front-vue/src/pages/Command.vue
agent/front-vue/src/pages/Dashboard.vue
agent/front-vue/src/pages/SocketIO.vue
agent/front-vue/src/router/routes.js
agent/monitoring/services.py

add router-view props
refactor code, change logic

change targetAddress receive style

---

agent/front-vue/src/pages/History.vue
agent/monitoring/controllers.py
agent/monitoring/services.py

Show how many databases are stored in mongodb.
Fix lint issues

Enable 'end' range at History.vue

---

agent/front-vue/src/pages/Command.vue
agent/front-vue/src/pages/Dashboard.vue
agent/front-vue/src/pages/SocketIO.vue
agent/front-vue/src/store.js

Add managing target address to local session storage

---

agent/front-vue/src/components/Command.vue
agent/monitoring/services.py

Add multiple command support

---

agent/app/__init__.py
agent/front-vue/src/components/Command.vue
agent/front-vue/src/layout/Breadcrumb.vue
agent/front-vue/src/pages/CommandTabs.vue
agent/front-vue/src/pages/Dashboard.vue
agent/front-vue/src/pages/History.vue
agent/monitoring/controllers.py
agent/monitoring/models.py
agent/monitoring/services.py

Add new REST endpoint ('/devices')
You should do db.data.renameCollection('datas') at mongo

Add mac_addr selector in History

---

guider/guider.py

printdir - add json result

---

guider/guider.py

Debugger: Fix infinite remote read

---

guider/guider.py

btrace: Fix arg value 0 issues

---

guider/guider.py

strace: Add list option

---

manager/admin-web/LICENSE
manager/admin-web/README.md
manager/admin-web/package.json
manager/admin-web/src/localization/strings.js

I have added the LICENSE documentation. And I modified README.md to improve usage. Also, I modified some text in Package.json to change the status value.

docs: LICENSE document addition and various text changes

---

guider/guider.py

btrace: Fix various command bugs

---

guider/guider.py
utils/reindent.py

btrace: Add CMD field for setret command

---

guider/guider.py

strace: Convert request arg for ptrace
btrace: Add map command
btrace: Add RET filter for elapsed time of calls

Add commands and args for btrace and strace

---

guider/guider.py
utils/ImplAnalyzer/ImplAnalyzer.py

ImplAnalyzer: Support glob pattern for path

---

guider/guider.py

ElfAnalyzer: Add DWARF CIE parser

---

guider/guider.py

option: Add generalInfo option

---

guider/guider.py

ElfAnalyzer: Add DWARF CONSTANTS

---

guider/guider.py

This code supports JSON-format tracing output with -J option.

btrace: Support JSON-format output (#270)

---

guider/guider.py

pytrace: Support JSON-format output

---

guider/guider.py

It will combine contexts for entry and exit in function call,
So the output for a function call will be displayed in a line.

btrace: Combine contexts for entry and exit in function call

---

guider/guider.py

statement: Apply augmented assignment statements (#266)

---

guider/guider.py

strace: Support * character in filter

---

guider/guider.py

general: Add redirection option for standard I/O

---

guider/guider.py

struct: Remove redundant item in SYSCALL_PROTOTYPES (#281)

---

guider/guider.py

profile: Support filter for multiple target numbers

---

README.md

should appear shortly for debian, ubuntu...

add a link to guider prebuilt versions

---

guider/guider.py

rtop: Add specific file data

---

README.md
guider/guider.py

limitpid: Add limitpid commmand

---

guider/guider.py

exec: Add task filter for monitoring

---

guider/guider.py

printinfo: Add KSM and HugePage Info

---

guider/guider.py

printinfo: Remove redundant data

---

guider/guider.py

leaktrace: Add KEEPTASK variable

---

guider/guider.py

printcg: Add pressure info
